AWS_ACCESS_KEY_ID = "your_AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY = "your_AWS_SECRET_ACCESS_KEY"
AWS_DEFAULT_REGION = "your_AWS_DEFAULT_REGION"
bucket_name = "your_bucket_name"
model_path = "your_model_path_in_the_bucket"
standard_scaler_path = your_standard_scaler_path_in_the_bucket"